apiVersion: v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "php-info-pipeline", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        openshiftBuild 'php-info-pipeline-test'
      }
    }
    stage('Verify build') {
      steps {
        openshiftVerifyBuild 'php-info-pipeline-test'
      }
    }
    stage('Deploy') {
      steps {
        openshiftDeploy 'php-info-pipeline-test'
      }
    }
    stage('Verify Deployment') {
      steps {
        openshiftVerifyDeployment 'php-info-pipeline-test'
      }
    }
  }
}
"
  output:
  resources:
  postCommit:
