apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: your-pipeline
  name: your-pipeline
spec:
runPolicy: Serial
    source:
    git:
      uri: "https://github.com/BeXe/phpinfo/"
  strategy:
     type: JenkinsPipeline
     jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile-build
triggers:
  - github:
      secret: gitsecret
    type: GitHub
  - generic:
      secret: genericsecret
    type: Generic
