apiVersion: v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myphp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
    source:
    git:
      uri: "https://github.com/BeXe/phpinfo"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath:
  output:
  resources:
  postCommit:
